image: "redoxos/redoxer"

stages:
  - host
  - build

fmt:
  stage: host
  script:
      - rustup component add rustfmt
      - rustfmt --check

build:linux:
  stage: build
  before_script:
    - apt-get update
    - apt-get install cmake libfontconfig libsdl2-dev libfreetype6-dev libexpat1-dev -y
  script:
    - cargo +nightly build --bin background
    - cargo +nightly build --bin launcher
    - cargo +nightly build --bin orblogin
    - cargo +nightly build --bin calendar
    - cargo +nightly build --bin calculator
    - cargo +nightly build --bin viewer

build:redox:
  stage: build
  before_script:
    - apt-get update
    - apt-get install libfontconfig -y
  script:
    - redoxer build --bin background
    - redoxer build --bin launcher
    - redoxer build --bin orblogin
    - redoxer build --bin calendar
    - redoxer build --bin calculator
    - redoxer build --bin viewer
