// Single line text input field with Material Design Outline TextField look and feel.
// Reimplementation from the std-widgets of LineEdit
// to able to costumize its text and border color, see issue: https://github.com/slint-ui/slint/issues/1232

global LoginInputTheme {
    out property<length> height: 36px;
    out property<length> min-width: 100px;
    out property<brush> container-surface-brush: #282828;
    out property<brush> container-border-brush: #1D1D1D;
    out property<brush> container-focused-brush: white;
    out property<brush> container-disabled-border-brush: gray;
    out property<length> container-border-radius: 0px;
    out property<length> container-border-width: 2px;
    out property<length> container-focused-border-width: 2px;
    out property<length> layout-padding: 4px;
    out property<brush> placeholder-brush: lightgray;
    out property<relative-font-size> placeholder-font-size: 16 * 0.0625rem;
    out property<int> placeholder-font-weight: 200;
    out property<brush> input-brush: white;
    out property<brush> input-focused-brush: white;
    out property<relative-font-size> input-font-size: 16 * 0.0625rem;
    out property<int> input-font-weight: 600;
    out property<length> input-padding: 2px;
    out property<float> disabled-opacity: 0.38;
    out property<brush> container-error-border-brush:  #ED2839;
}
export component LoginInput {
    in property border-color <=> container.border-color;
    in property <length> font-size <=> input.font-size;
    in-out property <string> text <=> input.text;
    in property <string> placeholder-text <=> placeholder.text;
    out property <bool> has-focus: input.has-focus;
    in property <bool> enabled: input.enabled;
    in property input-type <=> input.input-type;
    in property horizontal-alignment <=> input.horizontal-alignment;
    in property read-only <=> input.read-only;
    // Indicates that the input has invalid credentials entered, reflect that visually
    in property <bool> has-error;
    callback accepted(string);
    callback edited(string);

    min-width: LoginInputTheme.min-width;
    height: LoginInputTheme.height;
    forward-focus: input;
    
    container := Rectangle {
        background: LoginInputTheme.container-surface-brush;
        width: 100%;
        height: 100%;
        border-radius: LoginInputTheme.container-border-radius;
        border-width: LoginInputTheme.container-border-width;
        border-color: LoginInputTheme.container-border-brush;
    }

    layout := HorizontalLayout {
        padding-left: LoginInputTheme.layout-padding;
        padding-right: LoginInputTheme.layout-padding;

        Rectangle {
            clip: true;

            placeholder := Text {
                width: 100%;
                height: 100%;
                color:  LoginInputTheme.placeholder-brush;
                font-size: LoginInputTheme.placeholder-font-size;
                font-weight: LoginInputTheme.placeholder-font-weight;
                visible: false;
                vertical-alignment: center;

                states [
                    empty when input.text == "" : {
                        visible: true;
                    }
                ]
            }

            input := TextInput {
                property <length> computed_x;
                property <length> padding-outer: layout.padding-left + layout.padding-right;

                x: min(0px, max(parent.width - self.width, self.computed_x));
                width: max(parent.width, self.preferred-width);
                height: 100%;
                color: LoginInputTheme.input-brush;
                vertical-alignment: center;
                font-size: LoginInputTheme.input-font-size;
                font-weight: LoginInputTheme.input-font-weight;
                padding: LoginInputTheme.input-padding;

                accepted => { root.accepted(self.text); }
                edited => { root.edited(self.text); }
                cursor-position-changed(cpos) => {
                    if (cpos.x + self.computed_x < self.padding-outer) {
                        self.computed_x = - cpos.x + self.padding-outer;
                    } else if (cpos.x + self.computed_x > parent.width - self.padding-outer) {
                        self.computed_x = parent.width - cpos.x - self.padding-outer;
                    }
                }
            }
        }
    }

    states [
        disabled when !root.enabled : {
            container.border-color: LoginInputTheme.container-disabled-border-brush;
            container.opacity: LoginInputTheme.disabled-opacity;
            input.opacity: LoginInputTheme.disabled-opacity;
            placeholder.opacity: LoginInputTheme.disabled-opacity;
        }
        focused when root.has-focus && !root.has-error: {
            container.border-width: LoginInputTheme.container-focused-border-width;
            container.border-color: LoginInputTheme.container-focused-brush;
            input.color:LoginInputTheme.input-focused-brush;
        }
        has-error when root.has-error: {
            container.border-color: LoginInputTheme.container-error-border-brush;
        }
    ]
}