import { Button } from "std-widgets.slint";
import { LoginTheme } from "./theme.slint";

export component LoginButton {
    in-out property text <=> txt.text;
    callback clicked <=> touch.clicked;

    min-width: max(LoginTheme.min-width-regular, layout.min-width);
    min-height: max(LoginTheme.height-regular, layout.min-height);

    skin := Rectangle {
        background: LoginTheme.button-background;
        border-color: LoginTheme.border-brush;
        border-radius: LoginTheme.border-radius;
        border-width: LoginTheme.border-width;
    }

    layout := HorizontalLayout {
        padding: 8px;

        txt := Text {
            color: LoginTheme.button-foreground;
            font-size: LoginTheme.font-size-regular;
            font-weight: LoginTheme.font-weight-bolder;
            horizontal-alignment: center;
        }

    }

    touch := TouchArea { }

    states [
        pressed when touch.pressed : {
            txt.color : LoginTheme.button-foreground-pressed;
        }
        hovered when touch.has-hover : {
            skin.background : LoginTheme.button-background.brighter(0.2);
        }
    ]
}
