export global LoginTheme {
    // Brushes
    out property <brush> border-brush: #1D1D1D;
    out property <brush> button-background: #274869;
    out property <brush> button-foreground: #eee;
    out property <brush> button-foreground-pressed: #fff;
    out property <brush> disabled-border-brush: gray;
    out property <brush> error-brush: #ED2839;
    out property <brush> input-background: #282828;
    out property <brush> input-placeholder-brush: lightgray;
    out property <brush> input-foreground: white;

    // Font sizes
    out property <int> font-weight-thin: 200;
    out property <int> font-weight-bold: 600;
    out property <int> font-weight-bolder: 800;

    out property <length> font-size-regular: 16px;
    out property <length> font-size-big: 18px;
    out property <length> font-size-bigger: 28px;
    out property <relative-font-size> font-size-regular-relative: 16 * 0.0625rem;

    // Lengths
    out property <length> border-radius: 0px;
    out property <length> border-width: 2px;
    out property <length> height-regular: 36px;

    // Padding
    out property <length> padding-small: 2px;
    out property <length> padding-regular: 8px;
    out property <length> min-width-regular: 100px;
    out property <length> v-spacing: 10px;

    out property<float> disabled-opacity: 0.38;
}